### ISSUE TITLE
Unable to locate the ionic.project file. Are you in your project directory? (CLI v1.6.1)

### ISSUE THREAD

**Issue by svennela** [ion-book/firebaseStarter#1]
Hi,

I am not able to start below app. Below is error i am running into. Please help.
ionic serve
Error occured [Error: Unable to locate the ionic.project file. Are you in your project directory?]

Unable to locate the ionic.project file. Are you in your project directory? (CLI v1.6.1)

Your system information:

Cordova CLI: 5.1.1
Gulp version:  CLI version 3.9.0
Gulp local:
Ionic CLI Version: 1.6.1
Ionic App Lib Version: 0.3.3
ios-deploy version: 1.7.0
ios-sim version: 4.1.1

**Comment by carlosrojaso** [comment]
mmm. you need create an Ionic Project First and replace the www/ directory. Or you can start one with:

    $ ionic start MyApp https://github.com/ion-book/firebaseStarter
